name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: puk06
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics-personal.svg

          base: header, activity, community, repositories, metadata
          base_indepth: yes

          plugin_languages: yes
          plugin_languages_indepth: no       
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 0%
          plugin_languages_limit: 10
          plugin_languages_ignored: ""

          repositories_forks: yes
          repositories_affiliations: owner, collaborator
